sonar.projectKey=sachinnishad98-sonarqube-ai-agent-v1-main-20260507074422
sonar.projectName=sonarqube-ai-agent-v1 (main) - 7/5/2026, 1:14:22 pm
sonar.projectVersion=1.0
sonar.sources=.
sonar.sourceEncoding=UTF-8
sonar.exclusions=node_modules/**,coverage/**,dist/**,build/**,.git/**,.claude/**,.wolf/**,**/*.test.js,**/*.spec.js
sonar.javascript.file.suffixes=.js,.jsx
sonar.typescript.file.suffixes=.ts,.tsx
sonar.host.url=http://localhost:9000
sonar.token=sqa_b8316400849f4a7a76678d3b60855590665e8c1b